---
- hosts: allhosts
  user: ginzburg
  sudo: yes
  tasks:
  - name: transfer script
    copy: src=/usr/local/ansible/res-ginzburg/cronreboot.sh dest=/tmp/cronreboot.sh mode=0555

  - name: Execute
    command: /bin/sh /tmp/cronreboot.sh
    async: 30
    poll: 5
